pipeline {
    agent any
    environment {
        IMAGE_REPO = "therealqi"
        IMAGE_NAME = "jenkins-lab02"
        IMAGE_TAG = "${BUILD_NUMBER}"
        WORKDIR = "CICD/lab02"
    }
    stages {
        stage('Run Unit Tests') {
            steps {
                dir(env.WORKDIR) {
                    sh 'mvn test'
                }
            }
        }
        stage('Build App') {
            steps {
                dir(env.WORKDIR) {
                    sh 'mvn clean package -DskipTests'
                }
            }
        }
        stage('Build Docker Image') {
            steps {
                dir(env.WORKDIR) {
                    sh 'docker build -t ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG} .'
                }
            }
        }
        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-creds', usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                    sh '''
                    echo ${DOCKERHUB_PASS} | docker login -u ${DOCKERHUB_USER} --password-stdin
                    docker push ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}
                '''
                }
            }
        }
        stage('Remove Local Docker Image') {
            steps {
                sh 'docker rmi ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG} || true'
            }
        }
        stage('Update Deployment YAML') {
            steps {
                dir(env.WORKDIR) {
                    sh '''
                  sed -i "s|image:.*|image: ${IMAGE_REPO}/${IMAGE_NAME}:${IMAGE_TAG}|g" app-deployment.yaml
                '''
                }
            }
        }
        stage('Deploy on K8s') {
            steps {
                withCredentials([file(credentialsId: 'kubeconfig', variable: 'KUBECONFIG_FILE')]) {
                    dir(env.WORKDIR) {
                        sh '''
                        export KUBECONFIG=$KUBECONFIG_FILE
                        kubectl apply -f app-deployment.yaml
                        '''
                    }
                }
            }
        }
    }
    post {
        always {
            echo "Pipeline finished."
        }
        success {
            echo "Pipeline succeeded!"
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}
