pipeline {
    agent any
    environment {
        APP_NAME = "jenkins-lab02"
        DOCKERHUB_CRED = credentials('dockerhub-creds')
    }
    stages {
        stage('Run Unit Tests') {
            steps {
                sh 'mvn test'
            }
        }
        stage('Build App') {
            steps {
                sh 'mvn package -DskipTests'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t ${APP_NAME}:${BUILD_NUMBER} .'
            }
        }
        stage('Push Docker Image') {
            steps {
                sh '''
                    echo ${DOCKERHUB_CRED_PSW} | docker login -u ${DOCKERHUB_CRED_USR} --password-stdin
                    docker tag ${APP_NAME}:${BUILD_NUMBER} ${DOCKERHUB_CRED_USR}/${APP_NAME}:latest
                    docker push ${DOCKERHUB_CRED_USR}/${APP_NAME}:latest
                '''
            }
        }
        stage('Remove Local Docker Image') {
            steps {
                sh 'docker rmi ${APP_NAME}:${BUILD_NUMBER} || true'
                sh 'docker rmi ${APP_NAME}:latest || true'
                sh 'docker rmi ${DOCKERHUB_CRED_USR}/${APP_NAME}:latest || true'
            }
        }
        stage('Update Deployment YAML') {
            steps {
                sh 'echo "Editing Deployment YAML"'
            }
        }
        stage('Deploy on K8s') {
            steps {
                sh 'kubectl get pods -n ivolve'
            }
        }
    }
    post {
        always { echo "Pipeline finished." }
        success { echo "Pipeline succeeded!" }
        failure { echo "Pipeline failed!" }
    }
}

