pipeline {
    agent any
    environment {
        APP_NAME = "jenkins-lab02"
        DOCKERHUB_CRED = credentials('dockerhub-creds')
    }
    stages {
        stage('Run Unit Tests') {
            sh 'mvn test'
        }
        stage('Build App.') {
            sh 'mvn package -DskipTests'
        }
        stage('Build Docker Image') {
            sh 'docker build -t ${APP_NAME}:${BUILD_NUMBER} .'
        }
        stage('Push Docker Image') {
            sh '''
                echo ${DOCKERHUB_CRED_PSW} | docker login -u ${DOCKERHUB_CRED_USR} --password-stdin
                docker tag ${APP_NAME}:${BUILD_NUMBER} ${DOCKERHUB_CRED_USR}/${APP_NAME}:latest
                docker push ${DOCKERHUB_CRED_USR}/${APP_NAME}:latest
            '''
        }
        stage('Remove Local Docker Image') {
            sh 'docker rmi ${APP_NAME}:${BUILD_NUMBER} || true'
            sh 'docker rmi ${DOCKERHUB_CRED_USR}/${APP_NAME}:latest || true'
        }
        stage('Update Deployment YAML') {
            sh 'echo "Editing Deployment YAML"'
        }
        stage('Deploy on K8s') {
            sh 'kubectl get pod -n ivolve'
        }
    }
    post {
        always {
            sh 'echo "Pipeline finished."'
        }
        success {
            sh 'echo "Pipeline succeeded!"'
        }
        failure {
            sh 'echo "Pipeline failed"'
        }
    }
}
